# Clean
[tasks.clean]
command = "cargo"
args = ["clean"]

# Test
[tasks.test]
command = "cargo"
args = ["test"]

# Lint
[tasks.lint]
script = '''
cargo clippy -- \
	-D clippy::all \
	-D clippy::pedantic \
	-D clippy::nursery \
	-D clippy::cargo \
	-A clippy::arithmetic_side_effects \
	-A clippy::integer_division \
	-A clippy::float_arithmetic \
	-A clippy::cast_precision_loss \
	-A clippy::missing-docs-in-private-items \
	-A clippy::implicit_return \
	-A clippy::separated_literal_suffix \
	-A clippy::std_instead_of_core \
	-A clippy::mod_module_files \
	-A clippy::option_if_let_else \
	-A clippy::missing_trait_methods \
	-A clippy::allow_attributes_without_reason \
	-A clippy::uninlined_format_args
'''

# License
[tasks.license-check]
install_crate = "rustfmt"
command = "cargo"
args = ["deny", "check"]

# Format

## Check
[tasks.rust-fmt-check]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--check"]

[tasks.toml-fmt-check]
install_crate = { crate_name = "taplo-cli", binary = "taplo", test_arg = "--help" }
command = "taplo"
args = ["fmt", "--check", "*.toml"]

[tasks.md-fmt-check]
command = "markdownlint"
args = ["*.md", "--config", ".markdownlint.jsonc"]

[tasks.fmt-check]
dependencies = ["rust-fmt-check", "toml-fmt-check", "md-fmt-check"]

## Fix
[tasks.rust-fmt-fix]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.toml-fmt-fix]
install_crate = { crate_name = "taplo-cli", binary = "taplo", test_arg = "--help" }
command = "taplo"
args = ["fmt", "*.toml"]

[tasks.md-fmt-fix]
command = "markdownlint"
args = ["*.md", "--config", ".markdownlint.jsonc", "--fix"]

[tasks.fmt-fix]
dependencies = ["rust-fmt-fix", "toml-fmt-fix", "md-fmt-fix"]

# Build
[tasks.release]
dependencies = ["clean"]
command = "cargo"
args = ["build", "--release"]

# Final
[tasks.build]
dependencies = ["fmt-fix", "lint", "test"]

[tasks.ci]
dependencies = ["fmt-check", "lint", "test", "release"]
